// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fx/gov/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryEGFParamsRequest is the request type for the Query/EGFParams RPC method.
type QuerySwitchParamsRequest struct {
}

func (m *QuerySwitchParamsRequest) Reset()         { *m = QuerySwitchParamsRequest{} }
func (m *QuerySwitchParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySwitchParamsRequest) ProtoMessage()    {}
func (*QuerySwitchParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47cb083fb0607b21, []int{0}
}
func (m *QuerySwitchParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySwitchParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySwitchParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySwitchParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySwitchParamsRequest.Merge(m, src)
}
func (m *QuerySwitchParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySwitchParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySwitchParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySwitchParamsRequest proto.InternalMessageInfo

// QueryEGFParamsResponse is the response type for the Query/EGFParams RPC
// method.
type QuerySwitchParamsResponse struct {
	Params SwitchParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QuerySwitchParamsResponse) Reset()         { *m = QuerySwitchParamsResponse{} }
func (m *QuerySwitchParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySwitchParamsResponse) ProtoMessage()    {}
func (*QuerySwitchParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47cb083fb0607b21, []int{1}
}
func (m *QuerySwitchParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySwitchParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySwitchParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySwitchParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySwitchParamsResponse.Merge(m, src)
}
func (m *QuerySwitchParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySwitchParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySwitchParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySwitchParamsResponse proto.InternalMessageInfo

func (m *QuerySwitchParamsResponse) GetParams() SwitchParams {
	if m != nil {
		return m.Params
	}
	return SwitchParams{}
}

// QueryCustomParamsRequest is the request type for the Query/CustomParams RPC
// method.
type QueryCustomParamsRequest struct {
	MsgUrl string `protobuf:"bytes,1,opt,name=msg_url,json=msgUrl,proto3" json:"msg_url,omitempty"`
}

func (m *QueryCustomParamsRequest) Reset()         { *m = QueryCustomParamsRequest{} }
func (m *QueryCustomParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCustomParamsRequest) ProtoMessage()    {}
func (*QueryCustomParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47cb083fb0607b21, []int{2}
}
func (m *QueryCustomParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCustomParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCustomParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCustomParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCustomParamsRequest.Merge(m, src)
}
func (m *QueryCustomParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCustomParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCustomParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCustomParamsRequest proto.InternalMessageInfo

func (m *QueryCustomParamsRequest) GetMsgUrl() string {
	if m != nil {
		return m.MsgUrl
	}
	return ""
}

// QueryCustomParamsResponse is the response type for the Query/CustomParams RPC
// method.
type QueryCustomParamsResponse struct {
	Params CustomParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryCustomParamsResponse) Reset()         { *m = QueryCustomParamsResponse{} }
func (m *QueryCustomParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCustomParamsResponse) ProtoMessage()    {}
func (*QueryCustomParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47cb083fb0607b21, []int{3}
}
func (m *QueryCustomParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCustomParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCustomParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCustomParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCustomParamsResponse.Merge(m, src)
}
func (m *QueryCustomParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCustomParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCustomParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCustomParamsResponse proto.InternalMessageInfo

func (m *QueryCustomParamsResponse) GetParams() CustomParams {
	if m != nil {
		return m.Params
	}
	return CustomParams{}
}

func init() {
	proto.RegisterType((*QuerySwitchParamsRequest)(nil), "fx.gov.v1.QuerySwitchParamsRequest")
	proto.RegisterType((*QuerySwitchParamsResponse)(nil), "fx.gov.v1.QuerySwitchParamsResponse")
	proto.RegisterType((*QueryCustomParamsRequest)(nil), "fx.gov.v1.QueryCustomParamsRequest")
	proto.RegisterType((*QueryCustomParamsResponse)(nil), "fx.gov.v1.QueryCustomParamsResponse")
}

func init() { proto.RegisterFile("fx/gov/v1/query.proto", fileDescriptor_47cb083fb0607b21) }

var fileDescriptor_47cb083fb0607b21 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x93, 0x72, 0x6f, 0x2f, 0x9d, 0xdb, 0xd5, 0xa0, 0xb6, 0x06, 0x89, 0x25, 0x16, 0x11,
	0xc1, 0x0c, 0x6d, 0x71, 0x2f, 0xf5, 0x05, 0x34, 0xe2, 0xc6, 0x4d, 0x49, 0xe3, 0x74, 0x1a, 0x68,
	0x72, 0xd2, 0xcc, 0x24, 0xb6, 0x14, 0x37, 0x82, 0x3b, 0x17, 0x82, 0x2f, 0xd5, 0x65, 0xc1, 0x8d,
	0x2b, 0x91, 0xd6, 0x07, 0x91, 0x4e, 0x42, 0x9b, 0xd2, 0x2a, 0xee, 0x0e, 0xc9, 0x7f, 0xfe, 0xef,
	0xe3, 0x24, 0x68, 0xbb, 0x33, 0x20, 0x0c, 0x62, 0x12, 0xd7, 0x48, 0x3f, 0xa2, 0xe1, 0xd0, 0x0c,
	0x42, 0x10, 0x80, 0x0b, 0x9d, 0x81, 0xc9, 0x20, 0x36, 0xe3, 0x9a, 0xb6, 0xb3, 0x4c, 0x04, 0x76,
	0x68, 0x7b, 0x3c, 0x89, 0x68, 0x5b, 0x0c, 0x18, 0xc8, 0x91, 0xcc, 0xa7, 0xf4, 0xe9, 0x1e, 0x03,
	0x60, 0x3d, 0x4a, 0xec, 0xc0, 0x25, 0xb6, 0xef, 0x83, 0xb0, 0x85, 0x0b, 0x7e, 0xba, 0x63, 0x68,
	0xa8, 0x7c, 0x39, 0xa7, 0x5c, 0xdd, 0xb9, 0xc2, 0xe9, 0x5e, 0xc8, 0x3a, 0x8b, 0xf6, 0x23, 0xca,
	0x85, 0x61, 0xa1, 0xdd, 0x0d, 0xef, 0x78, 0x00, 0x3e, 0xa7, 0xf8, 0x14, 0xe5, 0x13, 0x78, 0x59,
	0xad, 0xa8, 0x47, 0xff, 0xeb, 0x25, 0x73, 0x21, 0x68, 0x66, 0x17, 0x9a, 0x7f, 0xc6, 0xef, 0xfb,
	0x8a, 0x95, 0x86, 0x8d, 0x46, 0xca, 0x3b, 0x8f, 0xb8, 0x00, 0x6f, 0x85, 0x87, 0x4b, 0xe8, 0x9f,
	0xc7, 0x59, 0x2b, 0x0a, 0x7b, 0xb2, 0xb3, 0x60, 0xe5, 0x3d, 0xce, 0xae, 0xc3, 0xde, 0x42, 0x64,
	0x75, 0xe9, 0x17, 0x22, 0xd9, 0x85, 0x55, 0x91, 0xfa, 0x53, 0x0e, 0xfd, 0x95, 0xa5, 0x78, 0x84,
	0x8a, 0x59, 0x61, 0x7c, 0x90, 0x29, 0xf8, 0xee, 0x36, 0x5a, 0xf5, 0xe7, 0x50, 0xe2, 0x66, 0x54,
	0x1e, 0x5e, 0x3f, 0x5f, 0x72, 0x1a, 0x2e, 0x93, 0xe5, 0x27, 0xe3, 0x32, 0xd8, 0x4a, 0x34, 0xf0,
	0xa3, 0x8a, 0x8a, 0x59, 0xcb, 0x75, 0xfa, 0x86, 0x4b, 0xad, 0xd3, 0x37, 0x5d, 0xc6, 0x38, 0x96,
	0xf4, 0x2a, 0x36, 0x32, 0x74, 0x47, 0x06, 0x53, 0x3a, 0x19, 0xa5, 0xf7, 0xbe, 0x6f, 0x9e, 0x8d,
	0xa7, 0xba, 0x3a, 0x99, 0xea, 0xea, 0xc7, 0x54, 0x57, 0x9f, 0x67, 0xba, 0x32, 0x99, 0xe9, 0xca,
	0xdb, 0x4c, 0x57, 0x6e, 0x0e, 0x99, 0x2b, 0xba, 0x51, 0xdb, 0x74, 0xc0, 0x23, 0x41, 0xe4, 0xdf,
	0xba, 0xb6, 0x4b, 0x3a, 0x83, 0x13, 0x07, 0x42, 0x4a, 0x92, 0x5a, 0x31, 0x0c, 0x28, 0x6f, 0xe7,
	0xe5, 0x0f, 0xd5, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xca, 0xa3, 0xeb, 0xad, 0xc0, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	SwitchParams(ctx context.Context, in *QuerySwitchParamsRequest, opts ...grpc.CallOption) (*QuerySwitchParamsResponse, error)
	CustomParams(ctx context.Context, in *QueryCustomParamsRequest, opts ...grpc.CallOption) (*QueryCustomParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SwitchParams(ctx context.Context, in *QuerySwitchParamsRequest, opts ...grpc.CallOption) (*QuerySwitchParamsResponse, error) {
	out := new(QuerySwitchParamsResponse)
	err := c.cc.Invoke(ctx, "/fx.gov.v1.Query/SwitchParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CustomParams(ctx context.Context, in *QueryCustomParamsRequest, opts ...grpc.CallOption) (*QueryCustomParamsResponse, error) {
	out := new(QueryCustomParamsResponse)
	err := c.cc.Invoke(ctx, "/fx.gov.v1.Query/CustomParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	SwitchParams(context.Context, *QuerySwitchParamsRequest) (*QuerySwitchParamsResponse, error)
	CustomParams(context.Context, *QueryCustomParamsRequest) (*QueryCustomParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SwitchParams(ctx context.Context, req *QuerySwitchParamsRequest) (*QuerySwitchParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchParams not implemented")
}
func (*UnimplementedQueryServer) CustomParams(ctx context.Context, req *QueryCustomParamsRequest) (*QueryCustomParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomParams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SwitchParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySwitchParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SwitchParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fx.gov.v1.Query/SwitchParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SwitchParams(ctx, req.(*QuerySwitchParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CustomParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCustomParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CustomParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fx.gov.v1.Query/CustomParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CustomParams(ctx, req.(*QueryCustomParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fx.gov.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwitchParams",
			Handler:    _Query_SwitchParams_Handler,
		},
		{
			MethodName: "CustomParams",
			Handler:    _Query_CustomParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fx/gov/v1/query.proto",
}

func (m *QuerySwitchParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySwitchParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySwitchParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySwitchParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySwitchParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySwitchParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCustomParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCustomParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCustomParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MsgUrl) > 0 {
		i -= len(m.MsgUrl)
		copy(dAtA[i:], m.MsgUrl)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MsgUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCustomParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCustomParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCustomParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySwitchParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySwitchParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCustomParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgUrl)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCustomParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySwitchParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySwitchParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySwitchParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySwitchParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySwitchParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySwitchParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCustomParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCustomParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCustomParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCustomParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCustomParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCustomParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
