run:
  timeout: 5m
  tests: true
  go: '1.23'
  allow-parallel-runners: true

issues:
  max-same-issues: 10
  exclude-dirs:
    - 'types/legacy'
  exclude-files:
    - '.*\\legacy\\_.*\\.go$'
    - '.*\\legacy\\.go$'
    - '.*\\.sol\\.go$'
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"
    - ".*\\.pulsar\\.go$"

linters:
  enable:
    - gofumpt
    - unconvert
    - unparam
    - stylecheck
    - gocyclo
    - errorlint
    - prealloc
    - gocritic
    - gci
    - dogsled
    - gosec
    - errcheck
    - goconst
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - revive
    - typecheck
    - unused
    - thelper
    - copyloopvar
    - wastedassign
    - testifylint

linters-settings:
  staticcheck:
    checks: [ "all", "-SA1019" ]
  stylecheck:
    checks: [ "all", "-ST1003" ]
  gocyclo:
    min-complexity: 15
  gocritic:
    disabled-checks: [ "assignOp", "ifElseChain", "appendAssign" ]
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  dogsled:
    max-blank-identifiers: 6
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: false
  gosimple:
    checks: [ "all" ]
  gosec:
    excludes: [ "G115" ]
  gci:
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/functionx/fx-core)
  errcheck:
    check-type-assertions: false
    check-blank: false
  unused:
    field-writes-are-uses: false
    exported-fields-are-used: false
    local-variables-are-used: false
  revive:
    # https://golangci-lint.run/usage/linters/#revive
    enable-all-rules: true
    # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
    rules:
      - name: max-control-nesting
        disabled: false
        exclude:
          - "**/doctor.go"
      - name: blank-imports
        disabled: false
        exclude:
          - "**/app.go"
      - name: function-result-limit
        disabled: false
        arguments:
          - 4
      - name: unhandled-error
        arguments:
          - "fmt.Printf"
          - "fmt.Println"
          - "strings.Builder.WriteString"
      - name: var-naming
        arguments:
          - [ "ID", "IDS", "URL", "JSON", "RPC" ] # AllowList
          - [ "" ] # DenyList
          - - upperCaseConst: true

      - name: line-length-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: use-any
        disabled: true
      - name: add-constant
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: function-length
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: indent-error-flow
        disabled: true
      - name: argument-limit
        disabled: true
      - name: bare-return
        disabled: true
      - name: nested-structs
        disabled: true
      - name: unchecked-type-assertion
        disabled: true
      - name: comment-spacings
        disabled: true
