before:
  hooks:
    - go mod download

builds:
  - id: "fxcore-darwin"
    main: ./cmd/fxcored
    binary: fxcored
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo netgo ledger
      - -trimpath
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
  - id: "fxcore-darwin-arm64"
    main: ./cmd/fxcored
    binary: fxcored
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo netgo ledger
      - -trimpath
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
  - id: "fxcore-linux"
    main: ./cmd/fxcored
    binary: fxcored
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo netgo ledger
      - -trimpath
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
  - id: "fxcore-linux-arm64"
    main: ./cmd/fxcored
    binary: fxcored
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo netgo ledger
      - -trimpath
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
  - id: "fxcore-windows"
    main: ./cmd/fxcored
    binary: fxcored
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo netgo ledger
      - -trimpath
      - -buildmode=exe
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger

archives:
  - format: binary
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: SHA256SUMS-v{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: SNAPSHOT-{{ .Tag }}

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: keep-existing
  header: |
    # fxCore {{ .Tag }} Release Notes
  footer: |
    ## 🔨 Build from source
    
    ```bash
    git clone https://github.com/functionx/fx-core.git
    cd fx-core && git checkout {{ .Tag }}
    make install
    ```
    
    ## 🐳 Docker Images
    
    ```bash
    docker pull ghcr.io/functionx/fx-core:{{ .Version }}
    ```
    
    ```bash
    docker pull ghcr.io/functionx/fxcorevisor:{{ .Version }}
    ```
    
    ## ⚡️ Download binaries
    
    Binaries for linux, darwin, and windows are available below.
