before:
  hooks:
    - go mod download

builds:
  - id: "fxcore-darwin"
    main: ./cmd/fxcored
    binary: bin/fxcored
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo netgo ledger
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
  - id: "fxcore-darwin-arm64"
    main: ./cmd/fxcored
    binary: bin/fxcored
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo netgo ledger
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
  - id: "fxcore-linux"
    main: ./cmd/fxcored
    binary: bin/fxcored
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo netgo ledger
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
  - id: "fxcore-linux-arm64"
    main: ./cmd/fxcored
    binary: bin/fxcored
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo netgo ledger
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
  - id: "fxcore-windows"
    main: ./cmd/fxcored
    binary: bin/fxcored
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo netgo ledger
      - -buildmode=exe
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=fxcore -X github.com/cosmos/cosmos-sdk/version.AppName=fxcored -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - fxcore-darwin
      - fxcore-darwin-arm64
      - fxcore-windows
      - fxcore-linux
      - fxcore-linux-arm64

checksum:
  name_template: 'checksums.txt'

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: keep-existing
  header: |
    # fxCore {{ .Tag }} Release Notes
    
    ## ChangeLog
    * See [CHANGELOG.md](https://github.com/FunctionX/fx-core/blob/release/{{ .Tag }}/CHANGELOG.md) for details.

    ## Docker Images
    * fxcore: `ghcr.io/functionx/fx-core:{{ .Version }}`
    * cosmovisor: `ghcr.io/functionx/fxcorevisor:{{ .Version }}`

snapshot:
  name_template: "{{ .Tag }}-next"