#!/usr/bin/env bash

set -eo pipefail

CMDS='git go gofumpt goimports goimports-reviser'
STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

f_echo_stderr() {
  echo "$@" >&2
}

f_check_cmds() {
  for cmd in ${CMDS}; do
    which "${cmd}" &>/dev/null || f_echo_stderr "couldn't find ${cmd}, skipping"
  done
}

f_check_cmds

if [[ $STAGED_GO_FILES != "" ]]; then
  f_echo_stderr "[pre-commit] fmt'ing staged files..."
  for file in $STAGED_GO_FILES; do
    if [[ $file =~ build/ ]] || [[ $file =~ contract/ ]] || [[ $file =~ \.pb\.go ]]; then
      continue
    fi

    gofumpt -w -l "$file"
    goimports -w -local github.com/functionx/fx-core "$file"
    goimports-reviser -use-cache -rm-unused "$file"
    git add "$file"
  done
fi

# Run go mod tidy
go mod tidy && git add go.mod go.sum
