// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethereum/feemarket/v1/feemarket.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the EVM module parameters
type Params struct {
	// base fee change denominator bounds the amount the base fee can change
	// between blocks.
	BaseFeeChangeDenominator uint32 `protobuf:"varint,1,opt,name=base_fee_change_denominator,json=baseFeeChangeDenominator,proto3" json:"base_fee_change_denominator,omitempty" yaml:"base_fee_change_denominator"`
	// elasticity multiplier bounds the maximum gas limit an EIP-1559 block may
	// have.
	ElasticityMultiplier uint32 `protobuf:"varint,2,opt,name=elasticity_multiplier,json=elasticityMultiplier,proto3" json:"elasticity_multiplier,omitempty" yaml:"elasticity_multiplier"`
	// base fee for EIP-1559 blocks.
	BaseFee github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=base_fee,json=baseFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"base_fee" yaml:"base_fee"`
	// min base fee for EIP-1559 blocks.
	MinBaseFee github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=min_base_fee,json=minBaseFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"min_base_fee" yaml:"min_base_fee"`
	// max base fee for EIP-1559 blocks.
	MaxBaseFee github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=max_base_fee,json=maxBaseFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"max_base_fee" yaml:"max_base_fee"`
	// replace block max gas, if > 0
	MaxGas github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,6,opt,name=max_gas,json=maxGas,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"max_gas" yaml:"max_gas"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_644368932592b217, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBaseFeeChangeDenominator() uint32 {
	if m != nil {
		return m.BaseFeeChangeDenominator
	}
	return 0
}

func (m *Params) GetElasticityMultiplier() uint32 {
	if m != nil {
		return m.ElasticityMultiplier
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "fx.ethereum.feemarket.v1.Params")
}

func init() {
	proto.RegisterFile("ethereum/feemarket/v1/feemarket.proto", fileDescriptor_644368932592b217)
}

var fileDescriptor_644368932592b217 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0xd2, 0xcb, 0xca, 0xd3, 0x40,
	0x14, 0x07, 0xf0, 0x44, 0x6b, 0xaa, 0x83, 0x17, 0x88, 0x15, 0x82, 0x4a, 0x52, 0x06, 0x2c, 0xdd,
	0x34, 0xa1, 0xb8, 0x73, 0xa5, 0xf1, 0xbe, 0x10, 0x24, 0xe0, 0x42, 0x11, 0xc2, 0x34, 0x3d, 0x49,
	0x87, 0x66, 0x66, 0x4a, 0x66, 0x52, 0xd2, 0xb7, 0xf0, 0xb1, 0xba, 0xac, 0x3b, 0x71, 0x11, 0xa4,
	0x7d, 0x83, 0x3e, 0x81, 0x24, 0xbd, 0x24, 0x82, 0x7c, 0x50, 0xbe, 0x55, 0x92, 0xf9, 0xff, 0x39,
	0xbf, 0x0c, 0x1c, 0xf4, 0x0c, 0xd4, 0x0c, 0x32, 0xc8, 0x99, 0x17, 0x03, 0x30, 0x92, 0xcd, 0x41,
	0x79, 0xcb, 0x71, 0xf3, 0xe1, 0x2e, 0x32, 0xa1, 0x84, 0x69, 0xc5, 0x85, 0x7b, 0x6a, 0xba, 0x4d,
	0xb8, 0x1c, 0x3f, 0xee, 0x25, 0x22, 0x11, 0x75, 0xc9, 0xab, 0xde, 0x0e, 0x7d, 0xfc, 0xb3, 0x83,
	0x8c, 0xcf, 0x24, 0x23, 0x4c, 0x9a, 0x80, 0x9e, 0x4c, 0x88, 0x84, 0x30, 0x06, 0x08, 0xa3, 0x19,
	0xe1, 0x09, 0x84, 0x53, 0xe0, 0x82, 0x51, 0x4e, 0x94, 0xc8, 0x2c, 0xbd, 0xaf, 0x0f, 0xef, 0xf9,
	0x83, 0x7d, 0xe9, 0xe0, 0x15, 0x61, 0xe9, 0x0b, 0x7c, 0x45, 0x19, 0x07, 0x56, 0x95, 0xbe, 0x03,
	0x78, 0x5d, 0x67, 0x6f, 0x9a, 0xc8, 0xfc, 0x82, 0x1e, 0x41, 0x4a, 0xa4, 0xa2, 0x11, 0x55, 0xab,
	0x90, 0xe5, 0xa9, 0xa2, 0x8b, 0x94, 0x42, 0x66, 0xdd, 0xa8, 0x81, 0xfe, 0xbe, 0x74, 0x9e, 0x1e,
	0x80, 0xff, 0xd6, 0x70, 0xd0, 0x6b, 0xce, 0x3f, 0x9d, 0x8f, 0xcd, 0xef, 0xe8, 0xf6, 0xe9, 0x87,
	0xac, 0x9b, 0x7d, 0x7d, 0x78, 0xc7, 0x7f, 0xb5, 0x2e, 0x1d, 0xed, 0x77, 0xe9, 0x0c, 0x12, 0xaa,
	0x66, 0xf9, 0xc4, 0x8d, 0x04, 0xf3, 0x22, 0x21, 0x99, 0x90, 0xc7, 0xc7, 0x48, 0x4e, 0xe7, 0x9e,
	0x5a, 0x2d, 0x40, 0xba, 0x1f, 0xb9, 0xda, 0x97, 0xce, 0x83, 0x7f, 0x2f, 0x86, 0x83, 0xee, 0xf1,
	0x16, 0x66, 0x82, 0xee, 0x32, 0xca, 0xc3, 0xb3, 0xd0, 0xa9, 0x85, 0xb7, 0x17, 0x0b, 0x0f, 0x0f,
	0x42, 0x7b, 0x16, 0x0e, 0x10, 0xa3, 0xdc, 0x6f, 0x41, 0xa4, 0x68, 0xa0, 0x5b, 0xd7, 0x84, 0x5a,
	0xb3, 0x2a, 0x88, 0x14, 0x27, 0xe8, 0x2b, 0xea, 0x56, 0x61, 0x42, 0xa4, 0x65, 0xd4, 0xc6, 0xcb,
	0x8b, 0x8d, 0xfb, 0x8d, 0x91, 0x10, 0x89, 0x03, 0x83, 0x91, 0xe2, 0x3d, 0x91, 0xfe, 0x87, 0xf5,
	0xd6, 0xd6, 0x37, 0x5b, 0x5b, 0xff, 0xb3, 0xb5, 0xf5, 0x1f, 0x3b, 0x5b, 0xdb, 0xec, 0x6c, 0xed,
	0xd7, 0xce, 0xd6, 0xbe, 0xb9, 0xad, 0xd9, 0x71, 0xce, 0x23, 0x45, 0x05, 0x2f, 0xbc, 0xb8, 0x18,
	0x45, 0x22, 0x03, 0xaf, 0x68, 0xad, 0x76, 0xed, 0x4c, 0x8c, 0x7a, 0x49, 0x9f, 0xff, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0xcc, 0xda, 0x22, 0xfd, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxGas.Size()
		i -= size
		if _, err := m.MaxGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeemarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MaxBaseFee.Size()
		i -= size
		if _, err := m.MaxBaseFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeemarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.MinBaseFee.Size()
		i -= size
		if _, err := m.MinBaseFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeemarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BaseFee.Size()
		i -= size
		if _, err := m.BaseFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFeemarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.ElasticityMultiplier != 0 {
		i = encodeVarintFeemarket(dAtA, i, uint64(m.ElasticityMultiplier))
		i--
		dAtA[i] = 0x10
	}
	if m.BaseFeeChangeDenominator != 0 {
		i = encodeVarintFeemarket(dAtA, i, uint64(m.BaseFeeChangeDenominator))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeemarket(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeemarket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseFeeChangeDenominator != 0 {
		n += 1 + sovFeemarket(uint64(m.BaseFeeChangeDenominator))
	}
	if m.ElasticityMultiplier != 0 {
		n += 1 + sovFeemarket(uint64(m.ElasticityMultiplier))
	}
	l = m.BaseFee.Size()
	n += 1 + l + sovFeemarket(uint64(l))
	l = m.MinBaseFee.Size()
	n += 1 + l + sovFeemarket(uint64(l))
	l = m.MaxBaseFee.Size()
	n += 1 + l + sovFeemarket(uint64(l))
	l = m.MaxGas.Size()
	n += 1 + l + sovFeemarket(uint64(l))
	return n
}

func sovFeemarket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeemarket(x uint64) (n int) {
	return sovFeemarket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeemarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeeChangeDenominator", wireType)
			}
			m.BaseFeeChangeDenominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseFeeChangeDenominator |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElasticityMultiplier", wireType)
			}
			m.ElasticityMultiplier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ElasticityMultiplier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeemarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeemarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeemarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeemarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinBaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeemarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeemarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxBaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeemarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeemarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeemarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeemarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeemarket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeemarket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeemarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeemarket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeemarket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeemarket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeemarket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeemarket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeemarket = fmt.Errorf("proto: unexpected end of group")
)
