// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fx/crosschain/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState struct
type GenesisState struct {
	Params                  Params                  `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	LastObservedEventNonce  uint64                  `protobuf:"varint,2,opt,name=last_observed_event_nonce,json=lastObservedEventNonce,proto3" json:"last_observed_event_nonce,omitempty"`
	LastObservedBlockHeight LastObservedBlockHeight `protobuf:"bytes,3,opt,name=last_observed_block_height,json=lastObservedBlockHeight,proto3" json:"last_observed_block_height"`
	Oracles                 []Oracle                `protobuf:"bytes,4,rep,name=oracles,proto3" json:"oracles"`
	OracleSets              []OracleSet             `protobuf:"bytes,5,rep,name=oracle_sets,json=oracleSets,proto3" json:"oracle_sets"`
	BridgeTokens            []BridgeToken           `protobuf:"bytes,6,rep,name=bridge_tokens,json=bridgeTokens,proto3" json:"bridge_tokens"`
	UnbatchedTransfers      []OutgoingTransferTx    `protobuf:"bytes,7,rep,name=unbatched_transfers,json=unbatchedTransfers,proto3" json:"unbatched_transfers"`
	Batches                 []OutgoingTxBatch       `protobuf:"bytes,8,rep,name=batches,proto3" json:"batches"`
	OracleSetConfirms       []MsgOracleSetConfirm   `protobuf:"bytes,9,rep,name=oracle_set_confirms,json=oracleSetConfirms,proto3" json:"oracle_set_confirms"`
	BatchConfirms           []MsgConfirmBatch       `protobuf:"bytes,10,rep,name=batch_confirms,json=batchConfirms,proto3" json:"batch_confirms"`
	Attestations            []Attestation           `protobuf:"bytes,11,rep,name=attestations,proto3" json:"attestations"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_55adf565ef43ce68, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetLastObservedEventNonce() uint64 {
	if m != nil {
		return m.LastObservedEventNonce
	}
	return 0
}

func (m *GenesisState) GetLastObservedBlockHeight() LastObservedBlockHeight {
	if m != nil {
		return m.LastObservedBlockHeight
	}
	return LastObservedBlockHeight{}
}

func (m *GenesisState) GetOracles() []Oracle {
	if m != nil {
		return m.Oracles
	}
	return nil
}

func (m *GenesisState) GetOracleSets() []OracleSet {
	if m != nil {
		return m.OracleSets
	}
	return nil
}

func (m *GenesisState) GetBridgeTokens() []BridgeToken {
	if m != nil {
		return m.BridgeTokens
	}
	return nil
}

func (m *GenesisState) GetUnbatchedTransfers() []OutgoingTransferTx {
	if m != nil {
		return m.UnbatchedTransfers
	}
	return nil
}

func (m *GenesisState) GetBatches() []OutgoingTxBatch {
	if m != nil {
		return m.Batches
	}
	return nil
}

func (m *GenesisState) GetOracleSetConfirms() []MsgOracleSetConfirm {
	if m != nil {
		return m.OracleSetConfirms
	}
	return nil
}

func (m *GenesisState) GetBatchConfirms() []MsgConfirmBatch {
	if m != nil {
		return m.BatchConfirms
	}
	return nil
}

func (m *GenesisState) GetAttestations() []Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "fx.gravity.crosschain.v1.GenesisState")
}

func init() { proto.RegisterFile("fx/crosschain/v1/genesis.proto", fileDescriptor_55adf565ef43ce68) }

var fileDescriptor_55adf565ef43ce68 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x1b, 0x56, 0x5a, 0x70, 0x3b, 0x24, 0x0c, 0x02, 0xaf, 0x87, 0x50, 0x40, 0x48, 0x43,
	0x62, 0x89, 0x0a, 0x27, 0x2e, 0x08, 0x8a, 0x10, 0x0c, 0x31, 0x3a, 0x6d, 0x15, 0x07, 0x2e, 0x91,
	0xe3, 0x3a, 0x6e, 0xb4, 0xd6, 0xae, 0xfc, 0x77, 0xab, 0xec, 0x2d, 0x78, 0x01, 0xde, 0x67, 0xc7,
	0x1d, 0x39, 0x21, 0xd4, 0xbe, 0x08, 0x8a, 0x93, 0x34, 0x1d, 0xa3, 0xeb, 0x6e, 0xd6, 0xff, 0xfb,
	0xbe, 0x9f, 0xbf, 0xfe, 0xad, 0x06, 0xb9, 0x51, 0xe2, 0x33, 0xad, 0x00, 0xd8, 0x90, 0xc6, 0xd2,
	0x9f, 0x75, 0x7c, 0xc1, 0x25, 0x87, 0x18, 0xbc, 0x89, 0x56, 0x46, 0x61, 0x12, 0x25, 0x9e, 0xd0,
	0x74, 0x16, 0x9b, 0x53, 0xaf, 0xf4, 0x79, 0xb3, 0x4e, 0x6b, 0xe7, 0x52, 0xd2, 0x24, 0x59, 0xa8,
	0xf5, 0xf8, 0x92, 0xb4, 0x12, 0xcd, 0x2c, 0xf7, 0x85, 0x12, 0xca, 0x1e, 0xfd, 0xf4, 0x94, 0x4d,
	0x9f, 0xfc, 0xac, 0xa3, 0xe6, 0xc7, 0xec, 0xfe, 0x63, 0x43, 0x0d, 0xc7, 0x6f, 0x50, 0x6d, 0x42,
	0x35, 0x1d, 0x03, 0x71, 0xda, 0xce, 0x6e, 0xe3, 0x65, 0xdb, 0x5b, 0xd7, 0xc7, 0x3b, 0xb4, 0xbe,
	0x6e, 0xf5, 0xec, 0xf7, 0xa3, 0xca, 0x51, 0x9e, 0xc2, 0xaf, 0xd1, 0xce, 0x88, 0x82, 0x09, 0x54,
	0x08, 0x5c, 0xcf, 0xf8, 0x20, 0xe0, 0x33, 0x2e, 0x4d, 0x20, 0x95, 0x64, 0x9c, 0xdc, 0x68, 0x3b,
	0xbb, 0xd5, 0xa3, 0x07, 0xa9, 0xa1, 0x97, 0xeb, 0x1f, 0x52, 0xf9, 0x6b, 0xaa, 0x62, 0x83, 0x5a,
	0x17, 0xa3, 0xe1, 0x48, 0xb1, 0x93, 0x60, 0xc8, 0x63, 0x31, 0x34, 0x64, 0xcb, 0xd6, 0xe9, 0xac,
	0xaf, 0xf3, 0x65, 0x85, 0xda, 0x4d, 0x93, 0x9f, 0x6c, 0x30, 0xef, 0xf7, 0x70, 0xf4, 0x7f, 0x19,
	0xbf, 0x45, 0x75, 0xa5, 0x29, 0x1b, 0x71, 0x20, 0xd5, 0xf6, 0xd6, 0xd5, 0xbf, 0xb8, 0x67, 0x8d,
	0x39, 0xb1, 0x88, 0xe1, 0xcf, 0xa8, 0x91, 0x1d, 0x03, 0xe0, 0x06, 0xc8, 0x4d, 0x4b, 0x79, 0xba,
	0x89, 0x72, 0xcc, 0x8b, 0x6a, 0x48, 0x15, 0x03, 0xc0, 0x87, 0x68, 0x3b, 0xd4, 0xf1, 0x40, 0xf0,
	0xc0, 0xa8, 0x13, 0x2e, 0x81, 0xd4, 0x2c, 0xed, 0xd9, 0x7a, 0x5a, 0xd7, 0xda, 0xfb, 0xa9, 0x3b,
	0xe7, 0x35, 0xc3, 0x72, 0x04, 0x98, 0xa1, 0x7b, 0x53, 0x19, 0x52, 0xc3, 0x86, 0x7c, 0x10, 0x18,
	0x4d, 0x25, 0x44, 0x5c, 0x03, 0xa9, 0x5b, 0xee, 0x8b, 0x2b, 0x5a, 0x4e, 0x8d, 0x50, 0xb1, 0x14,
	0xfd, 0x3c, 0xd2, 0x4f, 0x72, 0x3c, 0x5e, 0xe2, 0x0a, 0x09, 0xf0, 0x3e, 0xaa, 0x67, 0x33, 0x20,
	0xb7, 0x2c, 0xf8, 0xf9, 0x35, 0xc0, 0x49, 0x37, 0x8d, 0x14, 0xdb, 0xcc, 0xf3, 0x69, 0xdf, 0x72,
	0x9b, 0x01, 0x53, 0x32, 0x8a, 0xf5, 0x18, 0xc8, 0x6d, 0x8b, 0xdd, 0x5b, 0x8f, 0x3d, 0x00, 0xb1,
	0x5c, 0xec, 0xfb, 0x2c, 0x95, 0xa3, 0xef, 0xaa, 0x7f, 0xe6, 0x80, 0xbf, 0xa1, 0x3b, 0xf6, 0xbe,
	0x92, 0x8f, 0x36, 0xd5, 0x3e, 0x00, 0x51, 0x60, 0x57, 0x6a, 0x6f, 0x5b, 0xcc, 0x92, 0xdb, 0x43,
	0x4d, 0x6a, 0x0c, 0x07, 0x43, 0x4d, 0xac, 0x24, 0x90, 0xc6, 0xa6, 0xd7, 0x7b, 0x57, 0xba, 0x8b,
	0xd7, 0x5b, 0x05, 0x74, 0xf7, 0xcf, 0xe6, 0xae, 0x73, 0x3e, 0x77, 0x9d, 0x3f, 0x73, 0xd7, 0xf9,
	0xb1, 0x70, 0x2b, 0xe7, 0x0b, 0xb7, 0xf2, 0x6b, 0xe1, 0x56, 0xbe, 0xfb, 0x22, 0x36, 0xc3, 0x69,
	0xe8, 0x31, 0x35, 0xf6, 0xa3, 0xa9, 0x64, 0xa9, 0x3f, 0xf1, 0xa3, 0x64, 0x8f, 0x29, 0xcd, 0xfd,
	0x0b, 0x9f, 0x03, 0x73, 0x3a, 0xe1, 0x10, 0xd6, 0xec, 0x3f, 0xfe, 0xd5, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xfa, 0x42, 0xfd, 0x8b, 0x81, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.BatchConfirms) > 0 {
		for iNdEx := len(m.BatchConfirms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BatchConfirms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.OracleSetConfirms) > 0 {
		for iNdEx := len(m.OracleSetConfirms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleSetConfirms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.Batches) > 0 {
		for iNdEx := len(m.Batches) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Batches[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.UnbatchedTransfers) > 0 {
		for iNdEx := len(m.UnbatchedTransfers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UnbatchedTransfers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.BridgeTokens) > 0 {
		for iNdEx := len(m.BridgeTokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BridgeTokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.OracleSets) > 0 {
		for iNdEx := len(m.OracleSets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleSets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Oracles) > 0 {
		for iNdEx := len(m.Oracles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Oracles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.LastObservedBlockHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.LastObservedEventNonce != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastObservedEventNonce))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.LastObservedEventNonce != 0 {
		n += 1 + sovGenesis(uint64(m.LastObservedEventNonce))
	}
	l = m.LastObservedBlockHeight.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Oracles) > 0 {
		for _, e := range m.Oracles {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OracleSets) > 0 {
		for _, e := range m.OracleSets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BridgeTokens) > 0 {
		for _, e := range m.BridgeTokens {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.UnbatchedTransfers) > 0 {
		for _, e := range m.UnbatchedTransfers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Batches) > 0 {
		for _, e := range m.Batches {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OracleSetConfirms) > 0 {
		for _, e := range m.OracleSetConfirms {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BatchConfirms) > 0 {
		for _, e := range m.BatchConfirms {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastObservedEventNonce", wireType)
			}
			m.LastObservedEventNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastObservedEventNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastObservedBlockHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastObservedBlockHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oracles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Oracles = append(m.Oracles, Oracle{})
			if err := m.Oracles[len(m.Oracles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleSets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleSets = append(m.OracleSets, OracleSet{})
			if err := m.OracleSets[len(m.OracleSets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BridgeTokens = append(m.BridgeTokens, BridgeToken{})
			if err := m.BridgeTokens[len(m.BridgeTokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbatchedTransfers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnbatchedTransfers = append(m.UnbatchedTransfers, OutgoingTransferTx{})
			if err := m.UnbatchedTransfers[len(m.UnbatchedTransfers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Batches", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Batches = append(m.Batches, OutgoingTxBatch{})
			if err := m.Batches[len(m.Batches)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleSetConfirms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleSetConfirms = append(m.OracleSetConfirms, MsgOracleSetConfirm{})
			if err := m.OracleSetConfirms[len(m.OracleSetConfirms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchConfirms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchConfirms = append(m.BatchConfirms, MsgConfirmBatch{})
			if err := m.BatchConfirms[len(m.BatchConfirms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, Attestation{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
