# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package to npm

on:
  push:
    tags:
      - "solidity/v*.*.*"
  pull_request:
    paths:
      - 'solidity/**.sol'
      - 'solidity/package.json'
      - 'solidity/release.sh'
      - '.github/workflows/npm.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Set ENV
        id: env
        if: github.event_name != 'pull_request'
        run: echo "NODE_AUTH_TOKEN=${{secrets.NPM_TOKEN}}" >> $GITHUB_ENV

      - name: Release
        run: |
          chmod +x ./solidity/release.sh
          ./solidity/release.sh
        env:
          NODE_AUTH_TOKEN: ${{ steps.env.outputs.NODE_AUTH_TOKEN }}