name: Shell

on:
  push:
    branches:
      - main
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/shell.yml'

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run shellcheck
        run: make shell-lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install shfmt
        run: |
          wget https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64
          sudo mv shfmt_v3.8.0_linux_amd64 /usr/local/bin/shfmt
          sudo chmod +x /usr/local/bin/shfmt
      - name: Run shfmt
        run: |
          make shell-format
          git diff --exit-code
